name: Build Windows

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install
      - run: bun build --compile --target=bun-windows-x64 ./index.ts --outfile tsundere.exe
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: tsundere.exe
